### ISSUE TITLE
Generate HDF5 

### ISSUE THREAD

**Issue by igormaurell** [Hippogriff/parsenet-codebase#1]
Thanks for making the code available. I am training a parsenet with the provided dataset. When this is ready I will test with my own data, I would like to know how you transformed the dataset from CAD format to an HDF5 representation, some specific library was used? Or some other code public available? Thanks.

**Comment by Hippogriff** [comment]
It depends on the cad dataset you have. I was following ABC dataset format, that has information about parametric surface patches. I labeled mesh faces using this information, then sampled points on the meshes and transferred those face labels to points.
Also notice the shape normalization defined in `src/dataset.py` file, as this will be helpful in testing.

**Comment by igormaurell** [comment]
I am currently working in on CAD files from grabCAD that are in STEP format. I am using PCL to make the mesh faces and sample the points. But I am working in a way to get the label of the parametric surface for each mesh face and finally to the points. Do you have any idea how can I do this? Thanks.

**Comment by Hippogriff** [comment]
I didn't you step file. ABC dataset have step files and you can look into how to parse those files here: https://github.com/deep-geometry/abc-dataset. I am sorry, I can't be of much help there.

**Comment by Tomoki-0526** [comment]
Hello, I‘m strugging with the same problem about how to transfer CAD data to labeled point cloud. Have you found any method for that?
