### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by MulinYu** [Hippogriff/parsenet-codebase#6]
Hello,

Thanks for sharing the code.

Can you also provide the pre-trained model?

Best.
Mulin

**Comment by ZhaoyangZh** [comment]
Looking forward to the pre-trained model as well. Thanks a lot~

**Comment by Hippogriff** [comment]
Pre-trained models got deleted, unfortunately. I am training the models and post the link soon.

**Comment by Hippogriff** [comment]
You can find the pre-trained models here:

`http://neghvar.cs.umass.edu/public_data/parsenet/pretrained_models/`

**Comment by MulinYu** [comment]
Thanks a lot, it's helpful.

I used your script 'generate_predictions.py' to successfully generated 'seg_id' and 'pred_primitives', can you also provide a script to generate the parameters of primitives with the provided pre-trained model 'parsenet.pth'?

Thanks again.
Best.
Mulin

**Comment by MulinYu** [comment]
> You can find the pre-trained models here:
> 
> `http://neghvar.cs.umass.edu/public_data/parsenet/pretrained_models/`

**Comment by HowCCC** [comment]
> 您可以在此处找到预训练模型：
> 
> `http://neghvar.cs.umass.edu/public_data/parsenet/pretrained_models/`

hello, this site is unavailable right now, could you please share it to me in any way?

Such as my email: liushr6688@gmail.com

**Comment by shojint** [comment]
You can get the pretrained models of parsenet here
https://github.com/prs-eth/point2cad/tree/main/point2cad/logs/pretrained_models
